http {
    server {
        listen 8080;

        location / {
            root ./html/site1;
            index home.html;
            methods GET;
        }

        location /cgi-bin {
            root ./html/site1/cgi-bin;
            methods POST;
            cgi_ext .bla;
            cgi_path ./cgi_test;
        }

        location /post_body {
            methods POST;
            client_max_body_size 100;
        }

        location /directory {
            methods GET;
            root ./YoupiBanane;
            index youpi.bad_extension;
        }

        location /bla {
            methods POST;
            cgi_ext .bla;
            cgi_path ./cgi_test;
        }
    }
}